//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S7MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class atenciones_incidencias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public atenciones_incidencias()
        {
            this.atenciones_procesos_incidencias = new HashSet<atenciones_procesos_incidencias>();
        }
    
        public int ate_inc_idn { get; set; }
        public int ate_idn { get; set; }
        public int usu_pro_idn { get; set; }
        public int inc_idn { get; set; }
        public System.DateTime ate_inc_fecha_ingreso { get; set; }
        public string ate_inc_observacion { get; set; }
        public bool ate_inc_resuelta { get; set; }
        public string ate_inc_resolucion { get; set; }
        public Nullable<System.DateTime> ate_inc_fecha_resuelta { get; set; }
    
        public virtual atenciones atenciones { get; set; }
        public virtual incidencias incidencias { get; set; }
        public virtual usuarios_productos usuarios_productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atenciones_procesos_incidencias> atenciones_procesos_incidencias { get; set; }
    }
}
