//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S7MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class atenciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public atenciones()
        {
            this.atenciones_incidencias = new HashSet<atenciones_incidencias>();
        }
    
        public int ate_idn { get; set; }
        public int usu_idn { get; set; }
        public System.DateTime ate_fecha_ingreso { get; set; }
        public bool ate_cerrada { get; set; }
        public int emp_usu_sed_idn { get; set; }
    
        public virtual empresas_usuarios_sedes empresas_usuarios_sedes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atenciones_incidencias> atenciones_incidencias { get; set; }
    }
}
