//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S7MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class atenciones_procesos_incidencias
    {
        public int ate_pro_inc_idn { get; set; }
        public int ate_inc_idn { get; set; }
        public int pro_ges_inc_idn { get; set; }
        public string ate_pro_inc_observacion { get; set; }
        public System.DateTime ate_pro_inc_fecha_ingreso { get; set; }
        public int emp_usu_sed_idn { get; set; }
        public System.DateTime ate_pro_inc_fecha_inicio_atencion { get; set; }
        public Nullable<System.DateTime> ate_pro_inc_fecha_termino_atencion { get; set; }
    
        public virtual atenciones_incidencias atenciones_incidencias { get; set; }
        public virtual empresas_usuarios_sedes empresas_usuarios_sedes { get; set; }
        public virtual procesos_gestiones_incidencias procesos_gestiones_incidencias { get; set; }
    }
}
