//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S7MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresas_usuarios_sedes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empresas_usuarios_sedes()
        {
            this.atenciones = new HashSet<atenciones>();
            this.atenciones_procesos_incidencias = new HashSet<atenciones_procesos_incidencias>();
            this.productos = new HashSet<productos>();
        }
    
        public int emp_usu_sed_idn { get; set; }
        public int emp_idn { get; set; }
        public int usu_idn { get; set; }
        public int sed_idn { get; set; }
        public int car_idn { get; set; }
        public System.DateTime emp_usu_sed_fecha_ingreso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atenciones> atenciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atenciones_procesos_incidencias> atenciones_procesos_incidencias { get; set; }
        public virtual cargos cargos { get; set; }
        public virtual empresas empresas { get; set; }
        public virtual sedes sedes { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productos> productos { get; set; }
    }
}
