//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S7MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class incidencias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public incidencias()
        {
            this.atenciones_incidencias = new HashSet<atenciones_incidencias>();
        }
    
        public int inc_idn { get; set; }
        public string inc_nombre { get; set; }
        public Nullable<int> tip_inc_idn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atenciones_incidencias> atenciones_incidencias { get; set; }
        public virtual tipos_incidencias tipos_incidencias { get; set; }
    }
}
