//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S7MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sieteEntidades : DbContext
    {
        public sieteEntidades()
            : base("name=sieteEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<anos> anos { get; set; }
        public virtual DbSet<atenciones> atenciones { get; set; }
        public virtual DbSet<atenciones_incidencias> atenciones_incidencias { get; set; }
        public virtual DbSet<atenciones_procesos_incidencias> atenciones_procesos_incidencias { get; set; }
        public virtual DbSet<cargos> cargos { get; set; }
        public virtual DbSet<empresas> empresas { get; set; }
        public virtual DbSet<empresas_usuarios_sedes> empresas_usuarios_sedes { get; set; }
        public virtual DbSet<gestiones_incindecias> gestiones_incindecias { get; set; }
        public virtual DbSet<incidencias> incidencias { get; set; }
        public virtual DbSet<periodos> periodos { get; set; }
        public virtual DbSet<periodos_evaluaciones_gestiones> periodos_evaluaciones_gestiones { get; set; }
        public virtual DbSet<procesos_gestiones_incidencias> procesos_gestiones_incidencias { get; set; }
        public virtual DbSet<procesos_gestiones_incidencias_saltos> procesos_gestiones_incidencias_saltos { get; set; }
        public virtual DbSet<procesos_incidencias> procesos_incidencias { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<ramos> ramos { get; set; }
        public virtual DbSet<sedes> sedes { get; set; }
        public virtual DbSet<semaforo_periodos_evaluaciones> semaforo_periodos_evaluaciones { get; set; }
        public virtual DbSet<semaforos> semaforos { get; set; }
        public virtual DbSet<tipos_incidencias> tipos_incidencias { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<usuarios_productos> usuarios_productos { get; set; }
        public virtual DbSet<usuarios_productos_ramos> usuarios_productos_ramos { get; set; }
        public virtual DbSet<reportes> reportes { get; set; }
    }
}
