//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S7MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class procesos_incidencias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public procesos_incidencias()
        {
            this.procesos_gestiones_incidencias = new HashSet<procesos_gestiones_incidencias>();
            this.semaforo_periodos_evaluaciones = new HashSet<semaforo_periodos_evaluaciones>();
        }
    
        public int pro_inc_idn { get; set; }
        public string pro_inc_nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<procesos_gestiones_incidencias> procesos_gestiones_incidencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<semaforo_periodos_evaluaciones> semaforo_periodos_evaluaciones { get; set; }
    }
}
