//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S7MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class procesos_gestiones_incidencias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public procesos_gestiones_incidencias()
        {
            this.atenciones_procesos_incidencias = new HashSet<atenciones_procesos_incidencias>();
            this.procesos_gestiones_incidencias_saltos = new HashSet<procesos_gestiones_incidencias_saltos>();
            this.procesos_gestiones_incidencias_saltos1 = new HashSet<procesos_gestiones_incidencias_saltos>();
        }
    
        public int pro_ges_inc_idn { get; set; }
        public int pro_inc_idn { get; set; }
        public int ges_inc_idn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atenciones_procesos_incidencias> atenciones_procesos_incidencias { get; set; }
        public virtual gestiones_incindecias gestiones_incindecias { get; set; }
        public virtual procesos_incidencias procesos_incidencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<procesos_gestiones_incidencias_saltos> procesos_gestiones_incidencias_saltos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<procesos_gestiones_incidencias_saltos> procesos_gestiones_incidencias_saltos1 { get; set; }
    }
}
