//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S7MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.usuarios_productos = new HashSet<usuarios_productos>();
        }
    
        public int pro_idn { get; set; }
        public string pro_codigo_umas { get; set; }
        public string pro_nombre { get; set; }
        public int emp_usu_sed_idn { get; set; }
    
        public virtual empresas_usuarios_sedes empresas_usuarios_sedes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarios_productos> usuarios_productos { get; set; }
    }
}
