//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S7MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class semaforo_periodos_evaluaciones
    {
        public int sem_per_idn { get; set; }
        public int per_eva_ges_idn { get; set; }
        public int pro_inc_idn { get; set; }
        public int sem_idn { get; set; }
        public int sem_per_dias_desde { get; set; }
        public int sem_per_dias_hasta { get; set; }
    
        public virtual periodos_evaluaciones_gestiones periodos_evaluaciones_gestiones { get; set; }
        public virtual procesos_incidencias procesos_incidencias { get; set; }
        public virtual semaforos semaforos { get; set; }
    }
}
