//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S7MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios_productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios_productos()
        {
            this.atenciones_incidencias = new HashSet<atenciones_incidencias>();
            this.usuarios_productos_ramos = new HashSet<usuarios_productos_ramos>();
        }
    
        public int usu_pro_idn { get; set; }
        public int usu_idn { get; set; }
        public int pro_idn { get; set; }
        public int ano_idn { get; set; }
        public int per_idn { get; set; }
        public bool usu_pro_activo { get; set; }
    
        public virtual anos anos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atenciones_incidencias> atenciones_incidencias { get; set; }
        public virtual periodos periodos { get; set; }
        public virtual productos productos { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarios_productos_ramos> usuarios_productos_ramos { get; set; }
    }
}
