//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S7MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios_productos_ramos
    {
        public int usu_pro_ram_idn { get; set; }
        public int usu_pro_idn { get; set; }
        public int ram_idn { get; set; }
    
        public virtual ramos ramos { get; set; }
        public virtual usuarios_productos usuarios_productos { get; set; }
    }
}
